---
- name: install neomutt
  pkgng:
    name: neomutt
    state: present

- name: mutt->neomutt symlink
  file:
    src: /usr/local/bin/neomutt
    dest: /usr/local/bin/mutt
    state: link

- name: install msmtp
  pkgng:
    name: msmtp
    state: present

- name: mutt config
  template:
    dest: "/home/{{ system.username }}/.neomuttrc"
    src: muttrc
    mode: 0600
    owner: "{{ system.username }}"

- name: start a mutt tmux on reboot
  cron:
    name: start tmux/mutt on boot
    special_time: reboot
    job: tmux new -s email mutt
    user: "{{ system.username }}"

- import_tasks: sync.yml
- import_tasks: backup.yml
