---
- name: install isync
  pkgng:
    name: isync
    state: present

- name: isync config
  template:
    dest: "/home/{{ system.username }}/.mbsyncrc"
    src: mbsyncrc
    mode: 0600
    owner: "{{ system.username }}"

- name: gmail cert file
  copy:
    dest: "/home/{{ system.username }}/.gmail-cert.pem"
    src: gmail-cert.pem
    mode: 0600
    owner: "{{ system.username }}"

- name: mailsync script
  copy:
    dest: /usr/local/bin/mailsync
    src: mailsync
    mode: 0755
    owner: root

- name: hourly gmail sync cron
  cron:
    name: hourly gmail sync
    minute: 0
    job: /usr/local/bin/mailsync gmail
    user: "{{ system.username }}"
